#!/usr/bin/env bash
#
# Regenerate the Cloudflare IP include for nginx from the live published lists,
# then reload nginx only if the ranges actually changed.
#
# Design (same shape as the compiled cf-realip module, minus the binary):
#   fetch -> validate -> write-on-change -> nginx -t -> reload, with rollback.
# Safe to run on a schedule: a no-op when ranges are unchanged, and it never
# leaves a config nginx won't accept in place (validates, rolls back on fail).
#
# Writes:  $COLLABJS_DIR/nginx/cloudflare-ips.conf  (mounted into the container)
# Usage:   COLLABJS_DIR=/opt/collabjs ./scripts/update-cloudflare-ips.sh
# Schedule via scripts/systemd/cloudflare-ips.{service,timer}.
#
set -euo pipefail

PROJECT_DIR="${COLLABJS_DIR:-/opt/collabjs}"
OUT="$PROJECT_DIR/nginx/cloudflare-ips.conf"

# --- fetch + sanity-check BEFORE touching anything -------------------------
V4="$(curl -fsSL https://www.cloudflare.com/ips-v4)" || { echo "fetch of ips-v4 failed" >&2; exit 1; }
V6="$(curl -fsSL https://www.cloudflare.com/ips-v6)" || { echo "fetch of ips-v6 failed" >&2; exit 1; }
[[ -n "$V4" && -n "$V6" ]] || { echo "Cloudflare list was empty; aborting" >&2; exit 1; }

cidr_re='^[0-9a-fA-F:.]+/[0-9]+$'
for c in $V4 $V6; do
  [[ "$c" =~ $cidr_re ]] || { echo "malformed CIDR from Cloudflare: '$c'; aborting" >&2; exit 1; }
done

# --- build the new include -------------------------------------------------
tmp="$(mktemp)"
{
  echo "# AUTO-GENERATED by scripts/update-cloudflare-ips.sh — do not edit by hand."
  echo "# Source: cloudflare.com/ips-v4 + ips-v6"
  echo
  for c in $V4 $V6; do echo "set_real_ip_from $c;"; done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  echo
  echo 'geo $realip_remote_addr $from_cloudflare {'
  echo "    default 0;"
  for c in $V4 $V6; do echo "    $c 1;"; done
  echo "}"
} > "$tmp"

# --- no change? done -------------------------------------------------------
if [[ -f "$OUT" ]] && cmp -s "$tmp" "$OUT"; then
  echo "Cloudflare ranges unchanged; nothing to do."
  rm -f "$tmp"
  exit 0
fi

# --- stage new file, keeping a backup to roll back to ----------------------
backup=""
if [[ -f "$OUT" ]]; then
  backup="$(mktemp)"
  cp "$OUT" "$backup"
fi
cp "$tmp" "$OUT"
rm -f "$tmp"

# --- validate + reload, but only if the container is actually running ------
cd "$PROJECT_DIR"
if command -v docker >/dev/null 2>&1 && docker compose ps --status running nginx 2>/dev/null | grep -q nginx; then
  if docker compose exec -T nginx nginx -t; then
    docker compose exec -T nginx nginx -s reload
    echo "Cloudflare ranges updated; nginx reloaded."
  else
    # roll back to the last-known-good file so a future restart stays healthy
    if [[ -n "$backup" ]]; then mv "$backup" "$OUT"; else rm -f "$OUT"; fi
    echo "nginx -t rejected the new ranges; rolled back. Not reloaded." >&2
    exit 1
  fi
else
  echo "Wrote $OUT (nginx container not running; applies on next start)."
fi
rm -f "$backup" 2>/dev/null || true
